name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: [5.1, 5.2]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@master
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build --enable-test-discovery
    - name: Run tests
      run: swift test --enable-test-discovery
